### ISSUE TITLE
pybombs install gr-foo fails

### ISSUE THREAD

**Issue by jkbecker** [bastibl/gr-foo#22] opened 2019-12-17 01:48 UTC
Hi,

I am running into a weird bug on install that I don't understand and Google doesn't seem to help. Can you make sense of this?

``` 
$ pybombs -p pybombs-snout install --print-tree gr-foo
PyBOMBS.ConfigManager - INFO - Prefix Python version is: 3.6.9
PyBOMBS - INFO - PyBOMBS Version 2.3.3
PyBOMBS.install_manager - INFO - Phase 1: Creating install tree and installing binary packages:
Install tree:
|
\- gr-foo
PyBOMBS.install_manager - INFO - Phase 2: Recursively installing source packages to prefix:
PyBOMBS.install_manager - INFO - Installing package: gr-foo
PyBOMBS.Packager.source - WARNING - Build dir already exists: /home/jkbecker/pybombs-snout/src/gr-foo/build
Configuring: (100%) [================================================================================================]
PyBOMBS.Packager.source - WARNING - Configuration failed. Re-trying with higher verbosity.
-- UHD library found.
-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   filesystem
--   system
--   thread
--   chrono
--   date_time
--   atomic
-- Checking for module 'gmp'
--   No package 'gmp' found
-- Checking for module 'mpir >= 3.0'
--   No package 'mpir' found
-- Could NOT find MPIR (missing: MPIRXX_LIBRARY MPIR_LIBRARY MPIR_INCLUDE_DIR) 
CMake Error at CMakeLists.txt:102 (message):
  GnuRadio Runtime required to compile foo


-- Configuring incomplete, errors occurred!
See also "/home/jkbecker/pybombs-snout/src/gr-foo/build/CMakeFiles/CMakeOutput.log".
See also "/home/jkbecker/pybombs-snout/src/gr-foo/build/CMakeFiles/CMakeError.log".
PyBOMBS.Packager.source - ERROR - Configuration failed after running at least twice.
PyBOMBS.Packager.source - ERROR - Problem occurred while building package gr-foo:
Configuration failed
PyBOMBS.install_manager - ERROR - Error installing package gr-foo. Aborting.

```

**Comment by bastibl** [comment] 2019-12-17 10:21
grr, PyBombs... at some point they changed the gnuradio receipt to build` maint-3.8`. Now all receipts that depend on `gnuradio` are broken. gr-foo uses the `maint-3.7` branch of the module. It should use the `maint-3.8` branch. You can change this locally for now. I'll make  a PR for my modules.

**Comment by jkbecker** [comment] 2019-12-17 17:46
Ok, that's interesting... I retried on a fresh ubuntu 18.04 min installation to avoid any issues that could be the result of my setup (which had preexisting boost installed etc) and this is what I'm getting now (below).
Note that I installed pybombs via pip3 so I'd expect the interpreter to be python3, but it looks like UHD then switches to python2 and then mako doesn't exist for both...
This doesn't look like a gr-foo issue directly, but it definitely prevents its installation. I could not find a way to explicitly switch the interpreter for python for stuff that is called by pybombs, I'd assume it automatically uses its own variant (ie. python3 in my case?)...
I tried adding -DPYTHON_EXECUTABLE to various lines in the boost.lwr, but to no avail.

Note that the errors are identical whether I switch the gr-foo recipe to maint-3.7 or maint-3.8...

``` 
$ pybombs -p pybombs install gr-foo
PyBOMBS.ConfigManager - INFO - Prefix Python version is: 3.6.9
PyBOMBS - INFO - PyBOMBS Version 2.3.4a0
PyBOMBS.install_manager - INFO - Phase 1: Creating install tree and installing binary packages:
Install tree:
|
\- gr-foo
   |
   \- gnuradio
      |
      \- uhd
PyBOMBS.install_manager - INFO - Phase 2: Recursively installing source packages to prefix:
PyBOMBS.install_manager - INFO - Installing package: uhd
PyBOMBS.Packager.source - WARNING - Build dir already exists: /home/j/pybombs/src/uhd/host/build
Configuring: (100%) [===========================================================================]
PyBOMBS.Packager.source - WARNING - Configuration failed. Re-trying with higher verbosity.
-- 
-- Configuring the python interpreter...
-- Python interpreter: /usr/bin/python2
-- Override with: -DPYTHON_EXECUTABLE=<path-to-python>
-- Python runtime interpreter: /usr/bin/python2
-- Override with: -DRUNTIME_PYTHON_EXECUTABLE=<path-to-python>
-- Operating on release branch (UHD-3.14).
-- Using UHD Images Directory: /home/j/pybombs/share/uhd/images
-- 
-- Configuring Boost C++ Libraries...
-- Looking for optional Boost components...
-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   python
-- Looking for required Boost components...
-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   chrono
--   date_time
--   filesystem
--   program_options
--   regex
--   system
--   unit_test_framework
--   serialization
--   thread
--   atomic
-- Boost include directories: /usr/include
-- Boost library directories: /usr/lib/x86_64-linux-gnu
-- Boost libraries: /usr/lib/x86_64-linux-gnu/libboost_chrono.so;/usr/lib/x86_64-linux-gnu/libboost_date_time.so;/usr/lib/x86_64-linux-gnu/libboost_filesystem.so;/usr/lib/x86_64-linux-gnu/libboost_program_options.so;/usr/lib/x86_64-linux-gnu/libboost_regex.so;/usr/lib/x86_64-linux-gnu/libboost_system.so;/usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so;/usr/lib/x86_64-linux-gnu/libboost_serialization.so;/usr/lib/x86_64-linux-gnu/libboost_thread.so;/usr/lib/x86_64-linux-gnu/libboost_atomic.so;/usr/lib/x86_64-linux-gnu/libpthread.so
-- 
-- Python checking for Python version 2.7 or greater
-- Python checking for Python version 2.7 or greater - found
-- 
-- Python checking for Mako templates 0.4.2 or greater
-- Python checking for Mako templates 0.4.2 or greater - "import mako" failed
-- 
-- Python checking for requests 2.0 or greater
-- Python checking for requests 2.0 or greater - "import requests" failed
-- 
-- Python checking for numpy 1.7 or greater
-- Python checking for numpy 1.7 or greater - "import numpy" failed
-- 
-- Configuring LibUHD support...
--   Dependency Boost_FOUND = 1
--   Dependency HAVE_PYTHON_PLAT_MIN_VERSION = TRUE
--   Dependency HAVE_PYTHON_MODULE_MAKO = FALSE
CMake Error at cmake/Modules/UHDComponent.cmake:59 (message):
  Dependencies for required component LibUHD not met.
Call Stack (most recent call first):
  CMakeLists.txt:430 (LIBUHD_REGISTER_COMPONENT)


-- Configuring incomplete, errors occurred!
See also "/home/j/pybombs/src/uhd/host/build/CMakeFiles/CMakeOutput.log".
See also "/home/j/pybombs/src/uhd/host/build/CMakeFiles/CMakeError.log".
PyBOMBS.Packager.source - ERROR - Configuration failed after running at least twice.
PyBOMBS.Packager.source - ERROR - Problem occurred while building package uhd:
Configuration failed
PyBOMBS.install_manager - ERROR - Error installing package uhd. Aborting.
j@gnuradiotest:~$ pybombs -p pybombs install mako
PyBOMBS.ConfigManager - INFO - Prefix Python version is: 3.6.9
PyBOMBS - INFO - PyBOMBS Version 2.3.3
PyBOMBS.install_manager - INFO - Phase 1: Creating install tree and installing binary packages:
PyBOMBS.install_manager - INFO - No packages to install.
```

**Comment by bastibl** [comment] 2019-12-17 19:27
Looks like yet another PyBombs issue... I think most devs recommend to install GR and UHD (w/ devel packages) from the package manager. The current versions are quite recent and there is also a PPA https://launchpad.net/~gnuradio.

Regarding Python, using pip3 just means that PyBombs runs w/ Python3. But PyBombs is just a package manager, so it might install modules or dependencies that require Python2. It's a Python3 app that calls apt to install Python2 stuff. That's as intended and not an immediate problem.

You can start PyBombs with the verbose flag (or maybe several of them) to figure out what goes wrong. Wild guess: UHD depends on Mako and your system satisfies this because it has python3-mako. But then UHD uses Python2 and you don't have python-mako (i.e., the Python2 version of the package).
https://github.com/EttusResearch/uhd/blob/UHD-3.14/host/CMakeLists.txt#L286

**Comment by jkbecker** [comment] 2019-12-17 21:35
Update: Found a few things. One is IMO a pyBOMBS bug (in the process of filing it) and the other one is a UHD issue. I'll leave a message here with the references later, still waiting for my workarounds to build properly...

**Comment by jkbecker** [comment] 2019-12-17 21:56
Okay. Still working on the build to finish, but I identified these bugs that resulted in my problems above:

- PyBOMBS: https://github.com/gnuradio/pybombs/issues/565
- UHD: https://github.com/EttusResearch/uhd/issues/317

I will summarize a workaround & close after this build completes successfully.

**Comment by jkbecker** [comment] 2019-12-18 00:31
Got it to run by switching branches in all the recipes manually (change in recipe + `git checkout maint-3.8` manually in src folder thanks to the above bug).

FYI, this includes 80211 and 802154 - after switching branches everything worked like a charm.
Leaving this open so you can decide how to proceed, but IMO only the branch switching in the recipes in in your court.

Thanks for the quick responses!

**Comment by bastibl** [comment] 2019-12-18 14:37
Thanks for the feedback. I opened pull requests for my repos:
https://github.com/gnuradio/gr-recipes/pull/170
https://github.com/gnuradio/gr-etcetera/pull/83
I'll close this for now. Feel free to reopen if there are any other related issues.

**Closed by bastibl** 2019-12-18 14:37 UTC
